### PR TITLE
Feat/example config

### PR DESCRIPTION
**Pull request by misi**

### CODE REVIEW

**Comment by havfo** [comment]
I am not sure if we want to do this. To listen to those ports you need to be a privileged user, and we should prefer to NOT run as privileged user right? How about we add to the documentation what this means?

Add these lines (change ports and interface to fit):
`iptables -t nat -A PREROUTING -i bond0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 4443`
`ip6tables -t nat -A PREROUTING -i bond0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 4443`
`iptables -t nat -A PREROUTING -i bond0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080`
`ip6tables -t nat -A PREROUTING -i bond0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080`

**Comment by misi** [comment]
May there are workaround to run process unprivileged ports but listen ports
under 1024.

e.g
* CAP_NET_BIND_SERVICE and systemd
*https://en.m.wikipedia.org/wiki/Authbind

Misi

2018. nov. 12., Hét 15:49 dátummal Håvar Aambø Fosstveit <
notifications@github.com> ezt írta:

**Comment by misi** [comment]
@havfo 
May both way sould be documented.. 
I am fine also with iptables redirect..

What is your conclusion? Please advice..

**Comment by havfo** [comment]
The SystemD variant is perfectly fine, go for it. Please update the .service file.

**Comment by misi** [comment]
Done.
+ updated workdir.

**Comment by havfo** [comment]
Last thing, can you make pull request to RC1 branch?

**Comment by misi** [comment]
Sure. Done..

**Pull request merged**
