### PR TITLE
Create turkish language file

### PR DESCRIPTION
**Pull request by aliorhun**

### CODE REVIEW

**Comment by misi** [comment]
Many Thanks!

**Comment by misi** [comment]
@aliorhun  I just merged it to develop branch. Do you want to have it also in the master?

**Comment by misi** [comment]
I assumed yes so I merged it to master. Thanks again!

**Comment by aliorhun** [comment]
many thanks for your quick feedback.

**Comment by misi** [comment]
Anytime. Please join us and help to make it better...

**Comment by mertcelen** [comment]
It's not a quite right place to ask but... We are thinking of creating a deb package for quick installation. Are you interested? @misi

**Comment by misi** [comment]
@mertcelen  I am interested absolutely! We have a community list let's continue there maybe..

**Comment by havfo** [comment]
@mertcelen Sounds very good

**Pull request merged**
