### PR TITLE
Add autoMuteThreshold

### PR DESCRIPTION
**Pull request by misi**

### CODE REVIEW

**Comment by Astagor** [comment]
I think that you should add a permission BYPASS_AUTOMUTE, so we can have users, like moderators or admins, that don't get automatically muted.

**Comment by misi** [comment]
> I think that you should add a permission BYPASS_AUTOMUTE, so we can have users, like moderators or admins, that don't get automatically muted.

It is about just when you enter the room and I believe it should be a general thing. 
Anyone can unmute themselves after it. 
It is not a new feature. I just made the threshold configurable not hardcoded.

**Comment by Astagor** [comment]
Wow, what was the threshold before? I never had noticed it. When did you introduce it?

**Comment by L4ky** [comment]
I like this function but we should consider to add a popup when a user join that tells him he's muted and he needs to unmute.

**Comment by misi** [comment]
> I like this function but we should consider to add a popup when a user join that tells him he's muted and he needs to unmute.
It works already this way it  pops up the press the space to speak if user starts to speak. (Later it will work  voice activated transmit too.)

**Comment by L4ky** [comment]
> > I like this function but we should consider to add a popup when a user join that tells him he's muted and he needs to unmute.
> 
> It works already this way it pops up the press the space to speak if user starts to speak. (Later it will work voice activated transmit too.)

I know that but a real popup with current status ( like Zoom ) it's more understandable for common users.
You're muted and your webcam is off. 
Press these buttons to enable them.

**Comment by misi** [comment]
> > > I like this function but we should consider to add a popup when a user join that tells him he's muted and he needs to unmute.
> > 
> > 
> > It works already this way it pops up the press the space to speak if user starts to speak. (Later it will work voice activated transmit too.)
> 
> I know that but a real popup with current status ( like Zoom ) it's more understandable for common users.
> You're muted and your webcam is off.
> Press these buttons to enable them.
I am not sure if it is worth bugging every user everytime to press Ok on a pop-up.
As optional I am OK with it.
Please open a separate issue about it. 
The webcam is not off so not muted in our case only audio is muted.

**Comment by cap19** [comment]
What is automute? I read this but am unable to figure out what will setting it to 0 do to room size?

/**
	 * Set the auto mute / Push To Talk threshold
	 * default value is 4
	 * 
	 * Set it to 0 to disable auto mute functionality, 
	 * but use it with caution
	 * full mesh audio strongly decrease room capacity! 
	 */

**Pull request merged**
