### PR TITLE
Add Latvian (LV) localization, by Oskars Galanders

### PR DESCRIPTION
**Pull request by osering**
Localization of interface done by Oskars Galanders, to make this great free and open source software easily accessible for Latvian people

### CODE REVIEW

**Comment by misi** [comment]
Can you please help and do it for developer branch version for the Latvian translation too?

**Comment by osering** [comment]
Absolutely.

**Comment by misi** [comment]
@havfo  let's merge to master and also ask for it for develop too? What do you think?

**Comment by havfo** [comment]
The reason for doing it against develop is that develop has some more strings that need translating. Develop will also be merged back to master this week, so will be here soon anyway, good enough?

**Pull request closed without merging**
