### PR TITLE
Mistake (ignore)

### PR DESCRIPTION
**Pull request by mi4aux**
Some typo fix (also to have uniform variable naming, camel case)
Fix for the new/correct variable name in all translation files
Added/fixed .de (german) translation file

Switched event listener keypressed (deprecated) to keyup

Replaced static message with internationalized message

Off Topic: Wonderful work you have done, really - like it ;)

### CODE REVIEW

**Comment by misi** [comment]
Many many thanks!

**Comment by mi4aux** [comment]
You're welcome

Try to support / "give back" where i can ;)

**Comment by so010** [comment]
Thanks for your contribution!
Could you make this pull request into "develop" branch? You will see there will be conflicts because keypressed-issue is already addressed there ;) 
There is a typo in translations ("miccophoneUnMute")

**Comment by mi4aux** [comment]
Sure, placed new pull request into develop branch.
So this one can be removed.
;)

**Pull request closed without merging**
